// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/blockchain.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Block message
type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Height        int64                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	PreviousHash  string                 `protobuf:"bytes,3,opt,name=previous_hash,json=previousHash,proto3" json:"previous_hash,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Nonce         int64                  `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Difficulty    int32                  `protobuf:"varint,6,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Transactions  []*Transaction         `protobuf:"bytes,7,rep,name=transactions,proto3" json:"transactions,omitempty"`
	MerkleRoot    string                 `protobuf:"bytes,8,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_api_proto_blockchain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Block) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Block) GetPreviousHash() string {
	if x != nil {
		return x.PreviousHash
	}
	return ""
}

func (x *Block) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Block) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Block) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *Block) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *Block) GetMerkleRoot() string {
	if x != nil {
		return x.MerkleRoot
	}
	return ""
}

// Transaction message
type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Inputs        []*TxInput             `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs       []*TxOutput            `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_api_proto_blockchain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetInputs() []*TxInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *Transaction) GetOutputs() []*TxOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *Transaction) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Transaction Input
type TxInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Vout          int32                  `protobuf:"varint,2,opt,name=vout,proto3" json:"vout,omitempty"`
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	PublicKey     string                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxInput) Reset() {
	*x = TxInput{}
	mi := &file_api_proto_blockchain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxInput) ProtoMessage() {}

func (x *TxInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxInput.ProtoReflect.Descriptor instead.
func (*TxInput) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{2}
}

func (x *TxInput) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *TxInput) GetVout() int32 {
	if x != nil {
		return x.Vout
	}
	return 0
}

func (x *TxInput) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *TxInput) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

// Transaction Output
type TxOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	PublicKeyHash string                 `protobuf:"bytes,2,opt,name=public_key_hash,json=publicKeyHash,proto3" json:"public_key_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxOutput) Reset() {
	*x = TxOutput{}
	mi := &file_api_proto_blockchain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxOutput) ProtoMessage() {}

func (x *TxOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxOutput.ProtoReflect.Descriptor instead.
func (*TxOutput) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{3}
}

func (x *TxOutput) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TxOutput) GetPublicKeyHash() string {
	if x != nil {
		return x.PublicKeyHash
	}
	return ""
}

// UTXO message
type UTXO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Vout          int32                  `protobuf:"varint,2,opt,name=vout,proto3" json:"vout,omitempty"`
	Output        *TxOutput              `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UTXO) Reset() {
	*x = UTXO{}
	mi := &file_api_proto_blockchain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UTXO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UTXO) ProtoMessage() {}

func (x *UTXO) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UTXO.ProtoReflect.Descriptor instead.
func (*UTXO) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{4}
}

func (x *UTXO) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *UTXO) GetVout() int32 {
	if x != nil {
		return x.Vout
	}
	return 0
}

func (x *UTXO) GetOutput() *TxOutput {
	if x != nil {
		return x.Output
	}
	return nil
}

// Wallet message
type Wallet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // Private key should never be transmitted, only stored locally
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	mi := &file_api_proto_blockchain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{5}
}

func (x *Wallet) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Wallet) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

// Peer information
type PeerInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PeerId           string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Addresses        []string               `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	ConnectionStatus string                 `protobuf:"bytes,3,opt,name=connection_status,json=connectionStatus,proto3" json:"connection_status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_api_proto_blockchain_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{6}
}

func (x *PeerInfo) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *PeerInfo) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *PeerInfo) GetConnectionStatus() string {
	if x != nil {
		return x.ConnectionStatus
	}
	return ""
}

// Mining information
type MiningInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IsMining          bool                   `protobuf:"varint,1,opt,name=is_mining,json=isMining,proto3" json:"is_mining,omitempty"`
	BlocksMined       int64                  `protobuf:"varint,2,opt,name=blocks_mined,json=blocksMined,proto3" json:"blocks_mined,omitempty"`
	CurrentDifficulty int64                  `protobuf:"varint,3,opt,name=current_difficulty,json=currentDifficulty,proto3" json:"current_difficulty,omitempty"`
	HashRate          int64                  `protobuf:"varint,4,opt,name=hash_rate,json=hashRate,proto3" json:"hash_rate,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MiningInfo) Reset() {
	*x = MiningInfo{}
	mi := &file_api_proto_blockchain_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiningInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiningInfo) ProtoMessage() {}

func (x *MiningInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiningInfo.ProtoReflect.Descriptor instead.
func (*MiningInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{7}
}

func (x *MiningInfo) GetIsMining() bool {
	if x != nil {
		return x.IsMining
	}
	return false
}

func (x *MiningInfo) GetBlocksMined() int64 {
	if x != nil {
		return x.BlocksMined
	}
	return 0
}

func (x *MiningInfo) GetCurrentDifficulty() int64 {
	if x != nil {
		return x.CurrentDifficulty
	}
	return 0
}

func (x *MiningInfo) GetHashRate() int64 {
	if x != nil {
		return x.HashRate
	}
	return 0
}

// Blockchain information
type BlockchainInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Height            int64                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	BestBlockHash     string                 `protobuf:"bytes,2,opt,name=best_block_hash,json=bestBlockHash,proto3" json:"best_block_hash,omitempty"`
	Difficulty        int64                  `protobuf:"varint,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	TotalTransactions int64                  `protobuf:"varint,4,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	PeerCount         int64                  `protobuf:"varint,5,opt,name=peer_count,json=peerCount,proto3" json:"peer_count,omitempty"`
	IsSyncing         bool                   `protobuf:"varint,6,opt,name=is_syncing,json=isSyncing,proto3" json:"is_syncing,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BlockchainInfo) Reset() {
	*x = BlockchainInfo{}
	mi := &file_api_proto_blockchain_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockchainInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainInfo) ProtoMessage() {}

func (x *BlockchainInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainInfo.ProtoReflect.Descriptor instead.
func (*BlockchainInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{8}
}

func (x *BlockchainInfo) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockchainInfo) GetBestBlockHash() string {
	if x != nil {
		return x.BestBlockHash
	}
	return ""
}

func (x *BlockchainInfo) GetDifficulty() int64 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *BlockchainInfo) GetTotalTransactions() int64 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *BlockchainInfo) GetPeerCount() int64 {
	if x != nil {
		return x.PeerCount
	}
	return 0
}

func (x *BlockchainInfo) GetIsSyncing() bool {
	if x != nil {
		return x.IsSyncing
	}
	return false
}

type GetBlockByHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockByHashRequest) Reset() {
	*x = GetBlockByHashRequest{}
	mi := &file_api_proto_blockchain_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockByHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockByHashRequest) ProtoMessage() {}

func (x *GetBlockByHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockByHashRequest.ProtoReflect.Descriptor instead.
func (*GetBlockByHashRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{9}
}

func (x *GetBlockByHashRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type GetBlockByHeightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int64                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockByHeightRequest) Reset() {
	*x = GetBlockByHeightRequest{}
	mi := &file_api_proto_blockchain_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockByHeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockByHeightRequest) ProtoMessage() {}

func (x *GetBlockByHeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockByHeightRequest.ProtoReflect.Descriptor instead.
func (*GetBlockByHeightRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{10}
}

func (x *GetBlockByHeightRequest) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type GetBlockchainInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockchainInfoRequest) Reset() {
	*x = GetBlockchainInfoRequest{}
	mi := &file_api_proto_blockchain_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockchainInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockchainInfoRequest) ProtoMessage() {}

func (x *GetBlockchainInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockchainInfoRequest.ProtoReflect.Descriptor instead.
func (*GetBlockchainInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{11}
}

type GetBestBlockHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBestBlockHashRequest) Reset() {
	*x = GetBestBlockHashRequest{}
	mi := &file_api_proto_blockchain_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBestBlockHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBestBlockHashRequest) ProtoMessage() {}

func (x *GetBestBlockHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBestBlockHashRequest.ProtoReflect.Descriptor instead.
func (*GetBestBlockHashRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{12}
}

type GetBestBlockHashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBestBlockHashResponse) Reset() {
	*x = GetBestBlockHashResponse{}
	mi := &file_api_proto_blockchain_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBestBlockHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBestBlockHashResponse) ProtoMessage() {}

func (x *GetBestBlockHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBestBlockHashResponse.ProtoReflect.Descriptor instead.
func (*GetBestBlockHashResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{13}
}

func (x *GetBestBlockHashResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type GetBlockHeightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockHeightRequest) Reset() {
	*x = GetBlockHeightRequest{}
	mi := &file_api_proto_blockchain_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockHeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockHeightRequest) ProtoMessage() {}

func (x *GetBlockHeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockHeightRequest.ProtoReflect.Descriptor instead.
func (*GetBlockHeightRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{14}
}

type GetBlockHeightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int64                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockHeightResponse) Reset() {
	*x = GetBlockHeightResponse{}
	mi := &file_api_proto_blockchain_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockHeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockHeightResponse) ProtoMessage() {}

func (x *GetBlockHeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockHeightResponse.ProtoReflect.Descriptor instead.
func (*GetBlockHeightResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{15}
}

func (x *GetBlockHeightResponse) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_api_proto_blockchain_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{16}
}

func (x *GetTransactionRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

type SubmitTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTransactionRequest) Reset() {
	*x = SubmitTransactionRequest{}
	mi := &file_api_proto_blockchain_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTransactionRequest) ProtoMessage() {}

func (x *SubmitTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTransactionRequest.ProtoReflect.Descriptor instead.
func (*SubmitTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{17}
}

func (x *SubmitTransactionRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type SubmitTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTransactionResponse) Reset() {
	*x = SubmitTransactionResponse{}
	mi := &file_api_proto_blockchain_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTransactionResponse) ProtoMessage() {}

func (x *SubmitTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTransactionResponse.ProtoReflect.Descriptor instead.
func (*SubmitTransactionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{18}
}

func (x *SubmitTransactionResponse) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *SubmitTransactionResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SubmitTransactionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetMempoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMempoolRequest) Reset() {
	*x = GetMempoolRequest{}
	mi := &file_api_proto_blockchain_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMempoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMempoolRequest) ProtoMessage() {}

func (x *GetMempoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMempoolRequest.ProtoReflect.Descriptor instead.
func (*GetMempoolRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{19}
}

type GetMempoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMempoolResponse) Reset() {
	*x = GetMempoolResponse{}
	mi := &file_api_proto_blockchain_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMempoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMempoolResponse) ProtoMessage() {}

func (x *GetMempoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMempoolResponse.ProtoReflect.Descriptor instead.
func (*GetMempoolResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{20}
}

func (x *GetMempoolResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *GetMempoolResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetUTXORequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUTXORequest) Reset() {
	*x = GetUTXORequest{}
	mi := &file_api_proto_blockchain_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUTXORequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUTXORequest) ProtoMessage() {}

func (x *GetUTXORequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUTXORequest.ProtoReflect.Descriptor instead.
func (*GetUTXORequest) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{21}
}

func (x *GetUTXORequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetUTXOResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Utxos         []*UTXO                `protobuf:"bytes,1,rep,name=utxos,proto3" json:"utxos,omitempty"`
	TotalValue    int64                  `protobuf:"varint,2,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUTXOResponse) Reset() {
	*x = GetUTXOResponse{}
	mi := &file_api_proto_blockchain_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUTXOResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUTXOResponse) ProtoMessage() {}

func (x *GetUTXOResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUTXOResponse.ProtoReflect.Descriptor instead.
func (*GetUTXOResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{22}
}

func (x *GetUTXOResponse) GetUtxos() []*UTXO {
	if x != nil {
		return x.Utxos
	}
	return nil
}

func (x *GetUTXOResponse) GetTotalValue() int64 {
	if x != nil {
		return x.TotalValue
	}
	return 0
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_api_proto_blockchain_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{23}
}

func (x *GetBalanceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       int64                  `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	UtxoCount     int32                  `protobuf:"varint,2,opt,name=utxo_count,json=utxoCount,proto3" json:"utxo_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_api_proto_blockchain_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{24}
}

func (x *GetBalanceResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetBalanceResponse) GetUtxoCount() int32 {
	if x != nil {
		return x.UtxoCount
	}
	return 0
}

type GetPeerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeerInfoRequest) Reset() {
	*x = GetPeerInfoRequest{}
	mi := &file_api_proto_blockchain_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeerInfoRequest) ProtoMessage() {}

func (x *GetPeerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeerInfoRequest.ProtoReflect.Descriptor instead.
func (*GetPeerInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{25}
}

type GetPeerInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	PeerCount     int32                  `protobuf:"varint,2,opt,name=peer_count,json=peerCount,proto3" json:"peer_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeerInfoResponse) Reset() {
	*x = GetPeerInfoResponse{}
	mi := &file_api_proto_blockchain_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeerInfoResponse) ProtoMessage() {}

func (x *GetPeerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeerInfoResponse.ProtoReflect.Descriptor instead.
func (*GetPeerInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{26}
}

func (x *GetPeerInfoResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *GetPeerInfoResponse) GetPeerCount() int32 {
	if x != nil {
		return x.PeerCount
	}
	return 0
}

type ConnectPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Multiaddr     string                 `protobuf:"bytes,1,opt,name=multiaddr,proto3" json:"multiaddr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectPeerRequest) Reset() {
	*x = ConnectPeerRequest{}
	mi := &file_api_proto_blockchain_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectPeerRequest) ProtoMessage() {}

func (x *ConnectPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectPeerRequest.ProtoReflect.Descriptor instead.
func (*ConnectPeerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{27}
}

func (x *ConnectPeerRequest) GetMultiaddr() string {
	if x != nil {
		return x.Multiaddr
	}
	return ""
}

type ConnectPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectPeerResponse) Reset() {
	*x = ConnectPeerResponse{}
	mi := &file_api_proto_blockchain_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectPeerResponse) ProtoMessage() {}

func (x *ConnectPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectPeerResponse.ProtoReflect.Descriptor instead.
func (*ConnectPeerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{28}
}

func (x *ConnectPeerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectPeerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StartMiningRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinerAddress  string                 `protobuf:"bytes,1,opt,name=miner_address,json=minerAddress,proto3" json:"miner_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMiningRequest) Reset() {
	*x = StartMiningRequest{}
	mi := &file_api_proto_blockchain_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMiningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMiningRequest) ProtoMessage() {}

func (x *StartMiningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMiningRequest.ProtoReflect.Descriptor instead.
func (*StartMiningRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{29}
}

func (x *StartMiningRequest) GetMinerAddress() string {
	if x != nil {
		return x.MinerAddress
	}
	return ""
}

type StartMiningResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMiningResponse) Reset() {
	*x = StartMiningResponse{}
	mi := &file_api_proto_blockchain_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMiningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMiningResponse) ProtoMessage() {}

func (x *StartMiningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMiningResponse.ProtoReflect.Descriptor instead.
func (*StartMiningResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{30}
}

func (x *StartMiningResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartMiningResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopMiningRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopMiningRequest) Reset() {
	*x = StopMiningRequest{}
	mi := &file_api_proto_blockchain_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopMiningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopMiningRequest) ProtoMessage() {}

func (x *StopMiningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopMiningRequest.ProtoReflect.Descriptor instead.
func (*StopMiningRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{31}
}

type StopMiningResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopMiningResponse) Reset() {
	*x = StopMiningResponse{}
	mi := &file_api_proto_blockchain_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopMiningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopMiningResponse) ProtoMessage() {}

func (x *StopMiningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopMiningResponse.ProtoReflect.Descriptor instead.
func (*StopMiningResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{32}
}

func (x *StopMiningResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopMiningResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetMiningInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMiningInfoRequest) Reset() {
	*x = GetMiningInfoRequest{}
	mi := &file_api_proto_blockchain_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMiningInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMiningInfoRequest) ProtoMessage() {}

func (x *GetMiningInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMiningInfoRequest.ProtoReflect.Descriptor instead.
func (*GetMiningInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{33}
}

type SubscribeBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeBlocksRequest) Reset() {
	*x = SubscribeBlocksRequest{}
	mi := &file_api_proto_blockchain_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeBlocksRequest) ProtoMessage() {}

func (x *SubscribeBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeBlocksRequest.ProtoReflect.Descriptor instead.
func (*SubscribeBlocksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{34}
}

type SubscribeTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeTransactionsRequest) Reset() {
	*x = SubscribeTransactionsRequest{}
	mi := &file_api_proto_blockchain_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTransactionsRequest) ProtoMessage() {}

func (x *SubscribeTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTransactionsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{35}
}

type CreateWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletRequest) Reset() {
	*x = CreateWalletRequest{}
	mi := &file_api_proto_blockchain_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletRequest) ProtoMessage() {}

func (x *CreateWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletRequest.ProtoReflect.Descriptor instead.
func (*CreateWalletRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{36}
}

func (x *CreateWalletRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletRequest) Reset() {
	*x = GetWalletRequest{}
	mi := &file_api_proto_blockchain_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletRequest) ProtoMessage() {}

func (x *GetWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletRequest.ProtoReflect.Descriptor instead.
func (*GetWalletRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{37}
}

func (x *GetWalletRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ListWalletsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWalletsRequest) Reset() {
	*x = ListWalletsRequest{}
	mi := &file_api_proto_blockchain_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWalletsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWalletsRequest) ProtoMessage() {}

func (x *ListWalletsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWalletsRequest.ProtoReflect.Descriptor instead.
func (*ListWalletsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{38}
}

type ListWalletsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallets       []*Wallet              `protobuf:"bytes,1,rep,name=wallets,proto3" json:"wallets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWalletsResponse) Reset() {
	*x = ListWalletsResponse{}
	mi := &file_api_proto_blockchain_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWalletsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWalletsResponse) ProtoMessage() {}

func (x *ListWalletsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWalletsResponse.ProtoReflect.Descriptor instead.
func (*ListWalletsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{39}
}

func (x *ListWalletsResponse) GetWallets() []*Wallet {
	if x != nil {
		return x.Wallets
	}
	return nil
}

type GetWalletBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletBalanceRequest) Reset() {
	*x = GetWalletBalanceRequest{}
	mi := &file_api_proto_blockchain_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletBalanceRequest) ProtoMessage() {}

func (x *GetWalletBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetWalletBalanceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{40}
}

func (x *GetWalletBalanceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetWalletBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       int64                  `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletBalanceResponse) Reset() {
	*x = GetWalletBalanceResponse{}
	mi := &file_api_proto_blockchain_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletBalanceResponse) ProtoMessage() {}

func (x *GetWalletBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetWalletBalanceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{41}
}

func (x *GetWalletBalanceResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type SendTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAddress   string                 `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress     string                 `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTransactionRequest) Reset() {
	*x = SendTransactionRequest{}
	mi := &file_api_proto_blockchain_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTransactionRequest) ProtoMessage() {}

func (x *SendTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTransactionRequest.ProtoReflect.Descriptor instead.
func (*SendTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{42}
}

func (x *SendTransactionRequest) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *SendTransactionRequest) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *SendTransactionRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type SendTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTransactionResponse) Reset() {
	*x = SendTransactionResponse{}
	mi := &file_api_proto_blockchain_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTransactionResponse) ProtoMessage() {}

func (x *SendTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_blockchain_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTransactionResponse.ProtoReflect.Descriptor instead.
func (*SendTransactionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_blockchain_proto_rawDescGZIP(), []int{43}
}

func (x *SendTransactionResponse) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *SendTransactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendTransactionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_blockchain_proto protoreflect.FileDescriptor

const file_api_proto_blockchain_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/blockchain.proto\x12\n" +
	"blockchain\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa6\x02\n" +
	"\x05Block\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x03R\x06height\x12#\n" +
	"\rprevious_hash\x18\x03 \x01(\tR\fpreviousHash\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\x03R\x05nonce\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x06 \x01(\x05R\n" +
	"difficulty\x12;\n" +
	"\ftransactions\x18\a \x03(\v2\x17.blockchain.TransactionR\ftransactions\x12\x1f\n" +
	"\vmerkle_root\x18\b \x01(\tR\n" +
	"merkleRoot\"\xb4\x01\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x06inputs\x18\x02 \x03(\v2\x13.blockchain.TxInputR\x06inputs\x12.\n" +
	"\aoutputs\x18\x03 \x03(\v2\x14.blockchain.TxOutputR\aoutputs\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"o\n" +
	"\aTxInput\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12\x12\n" +
	"\x04vout\x18\x02 \x01(\x05R\x04vout\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\"H\n" +
	"\bTxOutput\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\x12&\n" +
	"\x0fpublic_key_hash\x18\x02 \x01(\tR\rpublicKeyHash\"]\n" +
	"\x04UTXO\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12\x12\n" +
	"\x04vout\x18\x02 \x01(\x05R\x04vout\x12,\n" +
	"\x06output\x18\x03 \x01(\v2\x14.blockchain.TxOutputR\x06output\"A\n" +
	"\x06Wallet\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\"n\n" +
	"\bPeerInfo\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\x12+\n" +
	"\x11connection_status\x18\x03 \x01(\tR\x10connectionStatus\"\x98\x01\n" +
	"\n" +
	"MiningInfo\x12\x1b\n" +
	"\tis_mining\x18\x01 \x01(\bR\bisMining\x12!\n" +
	"\fblocks_mined\x18\x02 \x01(\x03R\vblocksMined\x12-\n" +
	"\x12current_difficulty\x18\x03 \x01(\x03R\x11currentDifficulty\x12\x1b\n" +
	"\thash_rate\x18\x04 \x01(\x03R\bhashRate\"\xdd\x01\n" +
	"\x0eBlockchainInfo\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x03R\x06height\x12&\n" +
	"\x0fbest_block_hash\x18\x02 \x01(\tR\rbestBlockHash\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x03 \x01(\x03R\n" +
	"difficulty\x12-\n" +
	"\x12total_transactions\x18\x04 \x01(\x03R\x11totalTransactions\x12\x1d\n" +
	"\n" +
	"peer_count\x18\x05 \x01(\x03R\tpeerCount\x12\x1d\n" +
	"\n" +
	"is_syncing\x18\x06 \x01(\bR\tisSyncing\"+\n" +
	"\x15GetBlockByHashRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"1\n" +
	"\x17GetBlockByHeightRequest\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x03R\x06height\"\x1a\n" +
	"\x18GetBlockchainInfoRequest\"\x19\n" +
	"\x17GetBestBlockHashRequest\".\n" +
	"\x18GetBestBlockHashResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"\x17\n" +
	"\x15GetBlockHeightRequest\"0\n" +
	"\x16GetBlockHeightResponse\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x03R\x06height\",\n" +
	"\x15GetTransactionRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\"U\n" +
	"\x18SubmitTransactionRequest\x129\n" +
	"\vtransaction\x18\x01 \x01(\v2\x17.blockchain.TransactionR\vtransaction\"f\n" +
	"\x19SubmitTransactionResponse\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x13\n" +
	"\x11GetMempoolRequest\"g\n" +
	"\x12GetMempoolResponse\x12;\n" +
	"\ftransactions\x18\x01 \x03(\v2\x17.blockchain.TransactionR\ftransactions\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"*\n" +
	"\x0eGetUTXORequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"Z\n" +
	"\x0fGetUTXOResponse\x12&\n" +
	"\x05utxos\x18\x01 \x03(\v2\x10.blockchain.UTXOR\x05utxos\x12\x1f\n" +
	"\vtotal_value\x18\x02 \x01(\x03R\n" +
	"totalValue\"-\n" +
	"\x11GetBalanceRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"M\n" +
	"\x12GetBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x03R\abalance\x12\x1d\n" +
	"\n" +
	"utxo_count\x18\x02 \x01(\x05R\tutxoCount\"\x14\n" +
	"\x12GetPeerInfoRequest\"`\n" +
	"\x13GetPeerInfoResponse\x12*\n" +
	"\x05peers\x18\x01 \x03(\v2\x14.blockchain.PeerInfoR\x05peers\x12\x1d\n" +
	"\n" +
	"peer_count\x18\x02 \x01(\x05R\tpeerCount\"2\n" +
	"\x12ConnectPeerRequest\x12\x1c\n" +
	"\tmultiaddr\x18\x01 \x01(\tR\tmultiaddr\"I\n" +
	"\x13ConnectPeerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"9\n" +
	"\x12StartMiningRequest\x12#\n" +
	"\rminer_address\x18\x01 \x01(\tR\fminerAddress\"I\n" +
	"\x13StartMiningResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x13\n" +
	"\x11StopMiningRequest\"H\n" +
	"\x12StopMiningResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x16\n" +
	"\x14GetMiningInfoRequest\"\x18\n" +
	"\x16SubscribeBlocksRequest\"\x1e\n" +
	"\x1cSubscribeTransactionsRequest\")\n" +
	"\x13CreateWalletRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x10GetWalletRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x14\n" +
	"\x12ListWalletsRequest\"C\n" +
	"\x13ListWalletsResponse\x12,\n" +
	"\awallets\x18\x01 \x03(\v2\x12.blockchain.WalletR\awallets\"3\n" +
	"\x17GetWalletBalanceRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"4\n" +
	"\x18GetWalletBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x03R\abalance\"r\n" +
	"\x16SendTransactionRequest\x12!\n" +
	"\ffrom_address\x18\x01 \x01(\tR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x02 \x01(\tR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"b\n" +
	"\x17SendTransactionResponse\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xf6\n" +
	"\n" +
	"\x11BlockchainService\x12F\n" +
	"\x0eGetBlockByHash\x12!.blockchain.GetBlockByHashRequest\x1a\x11.blockchain.Block\x12J\n" +
	"\x10GetBlockByHeight\x12#.blockchain.GetBlockByHeightRequest\x1a\x11.blockchain.Block\x12U\n" +
	"\x11GetBlockchainInfo\x12$.blockchain.GetBlockchainInfoRequest\x1a\x1a.blockchain.BlockchainInfo\x12]\n" +
	"\x10GetBestBlockHash\x12#.blockchain.GetBestBlockHashRequest\x1a$.blockchain.GetBestBlockHashResponse\x12W\n" +
	"\x0eGetBlockHeight\x12!.blockchain.GetBlockHeightRequest\x1a\".blockchain.GetBlockHeightResponse\x12L\n" +
	"\x0eGetTransaction\x12!.blockchain.GetTransactionRequest\x1a\x17.blockchain.Transaction\x12`\n" +
	"\x11SubmitTransaction\x12$.blockchain.SubmitTransactionRequest\x1a%.blockchain.SubmitTransactionResponse\x12K\n" +
	"\n" +
	"GetMempool\x12\x1d.blockchain.GetMempoolRequest\x1a\x1e.blockchain.GetMempoolResponse\x12B\n" +
	"\aGetUTXO\x12\x1a.blockchain.GetUTXORequest\x1a\x1b.blockchain.GetUTXOResponse\x12K\n" +
	"\n" +
	"GetBalance\x12\x1d.blockchain.GetBalanceRequest\x1a\x1e.blockchain.GetBalanceResponse\x12N\n" +
	"\vGetPeerInfo\x12\x1e.blockchain.GetPeerInfoRequest\x1a\x1f.blockchain.GetPeerInfoResponse\x12N\n" +
	"\vConnectPeer\x12\x1e.blockchain.ConnectPeerRequest\x1a\x1f.blockchain.ConnectPeerResponse\x12N\n" +
	"\vStartMining\x12\x1e.blockchain.StartMiningRequest\x1a\x1f.blockchain.StartMiningResponse\x12K\n" +
	"\n" +
	"StopMining\x12\x1d.blockchain.StopMiningRequest\x1a\x1e.blockchain.StopMiningResponse\x12I\n" +
	"\rGetMiningInfo\x12 .blockchain.GetMiningInfoRequest\x1a\x16.blockchain.MiningInfo\x12J\n" +
	"\x0fSubscribeBlocks\x12\".blockchain.SubscribeBlocksRequest\x1a\x11.blockchain.Block0\x01\x12\\\n" +
	"\x15SubscribeTransactions\x12(.blockchain.SubscribeTransactionsRequest\x1a\x17.blockchain.Transaction0\x012\x9e\x03\n" +
	"\rWalletService\x12C\n" +
	"\fCreateWallet\x12\x1f.blockchain.CreateWalletRequest\x1a\x12.blockchain.Wallet\x12=\n" +
	"\tGetWallet\x12\x1c.blockchain.GetWalletRequest\x1a\x12.blockchain.Wallet\x12N\n" +
	"\vListWallets\x12\x1e.blockchain.ListWalletsRequest\x1a\x1f.blockchain.ListWalletsResponse\x12]\n" +
	"\x10GetWalletBalance\x12#.blockchain.GetWalletBalanceRequest\x1a$.blockchain.GetWalletBalanceResponse\x12Z\n" +
	"\x0fSendTransaction\x12\".blockchain.SendTransactionRequest\x1a#.blockchain.SendTransactionResponseB,Z*github.com/yourusername/bt/api/proto;protob\x06proto3"

var (
	file_api_proto_blockchain_proto_rawDescOnce sync.Once
	file_api_proto_blockchain_proto_rawDescData []byte
)

func file_api_proto_blockchain_proto_rawDescGZIP() []byte {
	file_api_proto_blockchain_proto_rawDescOnce.Do(func() {
		file_api_proto_blockchain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_blockchain_proto_rawDesc), len(file_api_proto_blockchain_proto_rawDesc)))
	})
	return file_api_proto_blockchain_proto_rawDescData
}

var file_api_proto_blockchain_proto_msgTypes = make([]protoimpl.MessageInfo, 44)
var file_api_proto_blockchain_proto_goTypes = []any{
	(*Block)(nil),                        // 0: blockchain.Block
	(*Transaction)(nil),                  // 1: blockchain.Transaction
	(*TxInput)(nil),                      // 2: blockchain.TxInput
	(*TxOutput)(nil),                     // 3: blockchain.TxOutput
	(*UTXO)(nil),                         // 4: blockchain.UTXO
	(*Wallet)(nil),                       // 5: blockchain.Wallet
	(*PeerInfo)(nil),                     // 6: blockchain.PeerInfo
	(*MiningInfo)(nil),                   // 7: blockchain.MiningInfo
	(*BlockchainInfo)(nil),               // 8: blockchain.BlockchainInfo
	(*GetBlockByHashRequest)(nil),        // 9: blockchain.GetBlockByHashRequest
	(*GetBlockByHeightRequest)(nil),      // 10: blockchain.GetBlockByHeightRequest
	(*GetBlockchainInfoRequest)(nil),     // 11: blockchain.GetBlockchainInfoRequest
	(*GetBestBlockHashRequest)(nil),      // 12: blockchain.GetBestBlockHashRequest
	(*GetBestBlockHashResponse)(nil),     // 13: blockchain.GetBestBlockHashResponse
	(*GetBlockHeightRequest)(nil),        // 14: blockchain.GetBlockHeightRequest
	(*GetBlockHeightResponse)(nil),       // 15: blockchain.GetBlockHeightResponse
	(*GetTransactionRequest)(nil),        // 16: blockchain.GetTransactionRequest
	(*SubmitTransactionRequest)(nil),     // 17: blockchain.SubmitTransactionRequest
	(*SubmitTransactionResponse)(nil),    // 18: blockchain.SubmitTransactionResponse
	(*GetMempoolRequest)(nil),            // 19: blockchain.GetMempoolRequest
	(*GetMempoolResponse)(nil),           // 20: blockchain.GetMempoolResponse
	(*GetUTXORequest)(nil),               // 21: blockchain.GetUTXORequest
	(*GetUTXOResponse)(nil),              // 22: blockchain.GetUTXOResponse
	(*GetBalanceRequest)(nil),            // 23: blockchain.GetBalanceRequest
	(*GetBalanceResponse)(nil),           // 24: blockchain.GetBalanceResponse
	(*GetPeerInfoRequest)(nil),           // 25: blockchain.GetPeerInfoRequest
	(*GetPeerInfoResponse)(nil),          // 26: blockchain.GetPeerInfoResponse
	(*ConnectPeerRequest)(nil),           // 27: blockchain.ConnectPeerRequest
	(*ConnectPeerResponse)(nil),          // 28: blockchain.ConnectPeerResponse
	(*StartMiningRequest)(nil),           // 29: blockchain.StartMiningRequest
	(*StartMiningResponse)(nil),          // 30: blockchain.StartMiningResponse
	(*StopMiningRequest)(nil),            // 31: blockchain.StopMiningRequest
	(*StopMiningResponse)(nil),           // 32: blockchain.StopMiningResponse
	(*GetMiningInfoRequest)(nil),         // 33: blockchain.GetMiningInfoRequest
	(*SubscribeBlocksRequest)(nil),       // 34: blockchain.SubscribeBlocksRequest
	(*SubscribeTransactionsRequest)(nil), // 35: blockchain.SubscribeTransactionsRequest
	(*CreateWalletRequest)(nil),          // 36: blockchain.CreateWalletRequest
	(*GetWalletRequest)(nil),             // 37: blockchain.GetWalletRequest
	(*ListWalletsRequest)(nil),           // 38: blockchain.ListWalletsRequest
	(*ListWalletsResponse)(nil),          // 39: blockchain.ListWalletsResponse
	(*GetWalletBalanceRequest)(nil),      // 40: blockchain.GetWalletBalanceRequest
	(*GetWalletBalanceResponse)(nil),     // 41: blockchain.GetWalletBalanceResponse
	(*SendTransactionRequest)(nil),       // 42: blockchain.SendTransactionRequest
	(*SendTransactionResponse)(nil),      // 43: blockchain.SendTransactionResponse
	(*timestamppb.Timestamp)(nil),        // 44: google.protobuf.Timestamp
}
var file_api_proto_blockchain_proto_depIdxs = []int32{
	44, // 0: blockchain.Block.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 1: blockchain.Block.transactions:type_name -> blockchain.Transaction
	2,  // 2: blockchain.Transaction.inputs:type_name -> blockchain.TxInput
	3,  // 3: blockchain.Transaction.outputs:type_name -> blockchain.TxOutput
	44, // 4: blockchain.Transaction.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 5: blockchain.UTXO.output:type_name -> blockchain.TxOutput
	1,  // 6: blockchain.SubmitTransactionRequest.transaction:type_name -> blockchain.Transaction
	1,  // 7: blockchain.GetMempoolResponse.transactions:type_name -> blockchain.Transaction
	4,  // 8: blockchain.GetUTXOResponse.utxos:type_name -> blockchain.UTXO
	6,  // 9: blockchain.GetPeerInfoResponse.peers:type_name -> blockchain.PeerInfo
	5,  // 10: blockchain.ListWalletsResponse.wallets:type_name -> blockchain.Wallet
	9,  // 11: blockchain.BlockchainService.GetBlockByHash:input_type -> blockchain.GetBlockByHashRequest
	10, // 12: blockchain.BlockchainService.GetBlockByHeight:input_type -> blockchain.GetBlockByHeightRequest
	11, // 13: blockchain.BlockchainService.GetBlockchainInfo:input_type -> blockchain.GetBlockchainInfoRequest
	12, // 14: blockchain.BlockchainService.GetBestBlockHash:input_type -> blockchain.GetBestBlockHashRequest
	14, // 15: blockchain.BlockchainService.GetBlockHeight:input_type -> blockchain.GetBlockHeightRequest
	16, // 16: blockchain.BlockchainService.GetTransaction:input_type -> blockchain.GetTransactionRequest
	17, // 17: blockchain.BlockchainService.SubmitTransaction:input_type -> blockchain.SubmitTransactionRequest
	19, // 18: blockchain.BlockchainService.GetMempool:input_type -> blockchain.GetMempoolRequest
	21, // 19: blockchain.BlockchainService.GetUTXO:input_type -> blockchain.GetUTXORequest
	23, // 20: blockchain.BlockchainService.GetBalance:input_type -> blockchain.GetBalanceRequest
	25, // 21: blockchain.BlockchainService.GetPeerInfo:input_type -> blockchain.GetPeerInfoRequest
	27, // 22: blockchain.BlockchainService.ConnectPeer:input_type -> blockchain.ConnectPeerRequest
	29, // 23: blockchain.BlockchainService.StartMining:input_type -> blockchain.StartMiningRequest
	31, // 24: blockchain.BlockchainService.StopMining:input_type -> blockchain.StopMiningRequest
	33, // 25: blockchain.BlockchainService.GetMiningInfo:input_type -> blockchain.GetMiningInfoRequest
	34, // 26: blockchain.BlockchainService.SubscribeBlocks:input_type -> blockchain.SubscribeBlocksRequest
	35, // 27: blockchain.BlockchainService.SubscribeTransactions:input_type -> blockchain.SubscribeTransactionsRequest
	36, // 28: blockchain.WalletService.CreateWallet:input_type -> blockchain.CreateWalletRequest
	37, // 29: blockchain.WalletService.GetWallet:input_type -> blockchain.GetWalletRequest
	38, // 30: blockchain.WalletService.ListWallets:input_type -> blockchain.ListWalletsRequest
	40, // 31: blockchain.WalletService.GetWalletBalance:input_type -> blockchain.GetWalletBalanceRequest
	42, // 32: blockchain.WalletService.SendTransaction:input_type -> blockchain.SendTransactionRequest
	0,  // 33: blockchain.BlockchainService.GetBlockByHash:output_type -> blockchain.Block
	0,  // 34: blockchain.BlockchainService.GetBlockByHeight:output_type -> blockchain.Block
	8,  // 35: blockchain.BlockchainService.GetBlockchainInfo:output_type -> blockchain.BlockchainInfo
	13, // 36: blockchain.BlockchainService.GetBestBlockHash:output_type -> blockchain.GetBestBlockHashResponse
	15, // 37: blockchain.BlockchainService.GetBlockHeight:output_type -> blockchain.GetBlockHeightResponse
	1,  // 38: blockchain.BlockchainService.GetTransaction:output_type -> blockchain.Transaction
	18, // 39: blockchain.BlockchainService.SubmitTransaction:output_type -> blockchain.SubmitTransactionResponse
	20, // 40: blockchain.BlockchainService.GetMempool:output_type -> blockchain.GetMempoolResponse
	22, // 41: blockchain.BlockchainService.GetUTXO:output_type -> blockchain.GetUTXOResponse
	24, // 42: blockchain.BlockchainService.GetBalance:output_type -> blockchain.GetBalanceResponse
	26, // 43: blockchain.BlockchainService.GetPeerInfo:output_type -> blockchain.GetPeerInfoResponse
	28, // 44: blockchain.BlockchainService.ConnectPeer:output_type -> blockchain.ConnectPeerResponse
	30, // 45: blockchain.BlockchainService.StartMining:output_type -> blockchain.StartMiningResponse
	32, // 46: blockchain.BlockchainService.StopMining:output_type -> blockchain.StopMiningResponse
	7,  // 47: blockchain.BlockchainService.GetMiningInfo:output_type -> blockchain.MiningInfo
	0,  // 48: blockchain.BlockchainService.SubscribeBlocks:output_type -> blockchain.Block
	1,  // 49: blockchain.BlockchainService.SubscribeTransactions:output_type -> blockchain.Transaction
	5,  // 50: blockchain.WalletService.CreateWallet:output_type -> blockchain.Wallet
	5,  // 51: blockchain.WalletService.GetWallet:output_type -> blockchain.Wallet
	39, // 52: blockchain.WalletService.ListWallets:output_type -> blockchain.ListWalletsResponse
	41, // 53: blockchain.WalletService.GetWalletBalance:output_type -> blockchain.GetWalletBalanceResponse
	43, // 54: blockchain.WalletService.SendTransaction:output_type -> blockchain.SendTransactionResponse
	33, // [33:55] is the sub-list for method output_type
	11, // [11:33] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_proto_blockchain_proto_init() }
func file_api_proto_blockchain_proto_init() {
	if File_api_proto_blockchain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_blockchain_proto_rawDesc), len(file_api_proto_blockchain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   44,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_blockchain_proto_goTypes,
		DependencyIndexes: file_api_proto_blockchain_proto_depIdxs,
		MessageInfos:      file_api_proto_blockchain_proto_msgTypes,
	}.Build()
	File_api_proto_blockchain_proto = out.File
	file_api_proto_blockchain_proto_goTypes = nil
	file_api_proto_blockchain_proto_depIdxs = nil
}
